apiVersion: v1
kind: ServiceAccount
metadata:
  name: snat-adjust-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: snat-adjust-controller-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: snat-adjust-controller
    namespace: default
---
#apiVersion: v1
#kind: Secret
#metadata:
#  namespace: default
#  name: snat-adjust-controller-secret
#type: Opaque
#stringData:
#  AK: "ENTER_YOUR_AK"
#  SK: "ENTER_YOUR_SK"
#  REGION: "ap-southeast-1"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: snat-adjust-controller-job
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: snat-adjust-controller
          serviceAccountName: snat-adjust-controller
          containers:
            - name: snat-adjust-controller-job
              image: alphagodzilla/byteplus-k8s-adjust-snat-controller:0.1.2
              imagePullPolicy: IfNotPresent
              env:
                - name: "AK"
                  valueFrom:
                    secretKeyRef:
                      name: "snat-adjust-controller-secret"
                      key: "AK"
                - name: "SK"
                  valueFrom:
                    secretKeyRef:
                      name: "snat-adjust-controller-secret"
                      key: "SK"
                - name: "REGION"
                  valueFrom:
                    secretKeyRef:
                      name: "snat-adjust-controller-secret"
                      key: "REGION"
          restartPolicy: Never
